// <auto-generated />
namespace Navtech.OMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddBuyerEmailAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBuyerEmailAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "202012240714115_AddBuyerEmailAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
